package org.example;
import java.time.LocalDate;
public class Date {

    static Run gotomain = new Run();

    public Date(){
        LocalDate currentDate = LocalDate.now();
    }

    public static void dateValidationPayment(LocalDate DateInMain){
        LocalDate currentDate = LocalDate.now();
        //currentDate is date generated by system during transaction
        //originalDate is date generated by system after login
        if (DateInMain.isEqual(currentDate)){
            System.out.println("Proceeding with transaction.");

        }else {
            System.out.println("Transaction denied due to error.");
            gotomain.main();
        }
    }


}
